obstacle_range: 2.5
raytrace_range: 3.0
#taking bot to be a box
footprint: [[0.005,0.005 ], [0.005, -0.005], [-0.005, -0.005] , [-0.005, 0.005]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_link , data_type: LaserScan, topic: dot/laser_scan, marking: true, clearing: true}
