obstacle_range: 2.5
raytrace_range: 3.0
#taking bot to be a box
footprint: [[0.005,0.005 ], [0.005, -0.005], [-0.005, -0.005] , [-0.005, 0.005]]
footprint_padding: 0.001
#robot_radius: ir_of_robot
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo_link , data_type: LaserScan, topic: dot/laser_scan, marking: true, clearing: true}
robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
resolution: 0.05

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: dot/laser_scan, inf_is_valid: true}

