image: grey.pgm 
resolution: 0.0017924496 #meters/pixel
origin: [-1.2192, -1.0683, 0.000000] #x,y,yaw of map
negate: 0 #white/black free/occupied or reverse
occupied_thresh: 0.85 #Pixels with occupancy probability greater than this threshold are considered completely occupied
free_thresh: 0.356 #Pixels with occupancy probability less than this threshold are considered completely free
